---

- hosts: all
  become: true
  tasks:

  - name: install apache and php 
    package:
      name: 
        - "{{ apache_packege}}"
        - "{{ php_packege }}"
      state: latest
      update_cache: yes
